words = [
    "autocmd",
    "basedpyright",
    "bufname",
    "bufnr",
    "bufs",
    "buftype",
    "closeoff",
    "cmd",
    "cmdheight",
    "cterm",
    "cursorline",
    "diffopt",
    "eob",
    "esc",
    "expandtab",
    "fillchars",
    "foldcolumn",
    "getcwd",
    "getqflist",
    "gopls",
    "gruvbox",
    "hiddenoff",
    "hlsearch",
    "ignorecase",
    "jsonls",
    "jumpoptions",
    "kanagawa",
    "keymaps",
    "linehl",
    "linematch",
    "lnum",
    "lspconfig",
    "lualine",
    "luarc",
    "nohls",
    "nohlsearch",
    "noremap",
    "nvim",
    "nvim",
    "olimorris",
    "omnifunc",
    "pwsh",
    "pycache",
    "pyright",
    "qflist",
    "setqflist",
    "shada",
    "shiftwidth",
    "showcmd",
    "showmode",
    "signcolumn",
    "smartcase",
    "softtabstop",
    "splitright",
    "statuscolumn",
    "swapfile",
    "sysname",
    "tabstop",
    "taplo",
    "textwidth",
    "timeoutlen",
    "venv",
    "wildignorecase",
    "winnr",
    "yamlls",
]
