local tw = require("treewalker")
vim.keymap.set("n", "<c-j>", tw.move_down, { noremap = true })
vim.keymap.set("n", "<c-k>", tw.move_up, { noremap = true })
vim.keymap.set("n", "<c-h>", tw.move_out, { noremap = true })
vim.keymap.set("n", "<c-l>", tw.move_in, { noremap = true })
