require("remaps.nvim.diagnostics")
require("remaps.nvim.jumps")
require("remaps.nvim.marks")
require("remaps.nvim.mouse")
require("remaps.nvim.panels")
-- require("remaps.nvim.persistent_marks")
require("remaps.nvim.quickfix")
require("remaps.nvim.remaps")
require("remaps.nvim.terminal")
