require("remaps.nvim.remaps")
require("remaps.nvim.marks")
require("remaps.nvim.panels")
require("remaps.nvim.terminal")
require("remaps.nvim.quickfix")
require("remaps.nvim.diagnostics")
require("remaps.nvim.jumps")
