vim.keymap.set({ "n" }, "<a-q>", "q", { noremap = true })
vim.keymap.set({ "n" }, "q", "", { noremap = true })
vim.keymap.set({ "c" }, "<c-h>", "<c-p>", { noremap = true })
vim.keymap.set({ "c" }, "<c-l>", "<c-n>", { noremap = true })
vim.keymap.set({ "c" }, "<c-k>", "<c-y>", { noremap = true })
