vim.keymap.set({ "n" }, "<a-q>", "q", { noremap = true })
vim.keymap.set({ "n" }, "q", "", { noremap = true })
vim.keymap.set({ "c" }, "<c-h>", "<c-p>", { noremap = true })
vim.keymap.set({ "c" }, "<c-l>", "<c-n>", { noremap = true })
vim.keymap.set({ "c" }, "<c-k>", "<c-y>", { noremap = true })
vim.keymap.set({ "n" }, "<c-i>", "<c-i>zz", { noremap = true })
vim.keymap.set({ "n" }, "<c-o>", "<c-o>zz", { noremap = true })
vim.keymap.set({ "n" }, "n", "nzz", { noremap = true })
vim.keymap.set({ "n" }, "N", "Nzz", { noremap = true })

vim.keymap.set({ "n" }, "/", function()
	vim.cmd("set nohls")
	vim.api.nvim_feedkeys("/", "n", true)
end, { noremap = true })
vim.keymap.set({ "n" }, "?", function()
	vim.cmd("set nohls")
	vim.api.nvim_feedkeys("?", "n", true)
end, { noremap = true })
vim.keymap.set({ "n" }, "*", function()
	vim.cmd("set nohls")
	vim.api.nvim_feedkeys("*", "n", true)
end, { noremap = true })
vim.keymap.set({ "n" }, "#", function()
	vim.cmd("set nohls")
	vim.api.nvim_feedkeys("#", "n", true)
end, { noremap = true })

if vim.loop.os_uname().sysname == "Windows_NT" then
	vim.api.nvim_create_user_command("OpenInExplorer", function()
		vim.cmd("silent !start explorer /select,%:p")
	end, {})
end
